### ISSUE TITLE
Support SVG elements

### ISSUE THREAD

**Issue by brainkim** [bikeshaving/crank#102]
Crank needs to use document.createElementNS to get SVG element working
https://github.com/bikeshaving/crank/discussions/38#discussioncomment-11672

We need to propagate whether we're in SVG down the tree somehow internally.

**Comment by jonrsawyer** [comment]
After updating to this release of Crank and making use of SVG in my MDC components, I'm getting lots of errors like the following:

```
TypeError: Cannot assign to read only property 'viewBox' of object '#<SVGSVGElement>'
```

I'll try to narrow it down.

**Comment by jonrsawyer** [comment]
Forgot to mention: both Chrome and Firefox manifest this issue.

Found this, likely to be applicable:

https://github.com/sveltejs/svelte/issues/2732

**Comment by brainkim** [comment]
A reproducible example would be appreciated! I’m having trouble understanding what people mean by “spread attributes” in the linked svelte issue, or why we would be attempting to assign to a property that doesn’t exist on the SVGSVGElement class.

My bad! JSDOM doesn’t seem to have great SVG support and I probably should have done some more testing 😓

**Comment by brainkim** [comment]
Moving to #117 to make tracking this easier.
