### ISSUE TITLE
using Context directly or expose CrankEventTarget class

### ISSUE THREAD

**Issue by ryhinchey** [bikeshaving/crank#116]
I'm currently using the `Context` class in the [router](https://github.com/ryhinchey/crank-realworld-example-app/blob/master/src/components/Router.js#L7) of the realworld example I'm working on.  I'm using it to create a "private" event system and do things like [this](https://github.com/ryhinchey/crank-realworld-example-app/blob/master/src/components/Router.js#L10).   I want to export simple functions that can dispatch events without them being tied to a component.

I'm porting the Router over to its own npm package and converting it to Typescript.  In doing so, TS is saying `Expected 1-2 arguments, but got 0.` when I do `const context = new Context()`.  

This made me think about using Context only for the event emitter and I've come to the conclusion that it's hacky.  I don't need everything the Context class provides and we already have `CrankEventTarget`.  

Perhaps the solve here is to expose the `CrankEventTarget` class as part Crank's public api?

**Comment by brainkim** [comment]
Hmmm yeah I don’t think the `Context` class is the right tool here. And we could expose `CrankEventTarget`, except it’s an internal detail that we probably want to change? My suggestion would be to use `EventTarget` directly? This mostly works in all browsers, and for safari you can use `event-target-shim`, the library we’re trying to redo lol. And then, if I’m reading your code right, it’s actually the perfect use case for use with provisions. You call `this.set` with the EventTarget in the Router, and access it with `this.get` in the `Link`. And you can hide the object, by using a symbol for a key for the provision.

**Comment by ryhinchey** [comment]
thanks @brainkim!
