### ISSUE TITLE
How does one use crank without a bundler?

### ISSUE THREAD

**Issue by Perrishnikov** [bikeshaving/crank#124]
How does one use crank without a bundler? Following the installation instructions as-is, did not work. "Uncaught SyntaxError: Unexpected token '<'"

**Comment by brainkim** [comment]
Hello! I’m sorry to hear you’re having trouble. I think I need some more information about your situation. Which instructions are you referring to? Also, if you’re using JSX, you necessarily need a transpilation step of some kind. Do you have a minimal example that I can look at?

**Comment by Perrishnikov** [comment]
Thanks for following up. I was following the Getting Started Installation instructions. Below is the code.
```
//index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Crank.js Test</title>
  </head>

  <body>
    <div id="app"></div>
    <script type="module" src="index.js"></script>
  </body>
</html>

//index.js
/** @jsx createElement */
import { createElement } from "https://unpkg.com/@bikeshaving/crank@0.1.6/esm/index.js";
// import { createElement } from "/web_modules/@bikeshaving/crank.js";
// import { Renderer } from '/web_modules/@bikeshaving/crank.js';
import { Renderer } from 'https://unpkg.com/@bikeshaving/crank@0.1.6/esm/index.js';

function Greeting({ name = "World" }) {
  return (
    <div>Hello {name}</div>
  );
}

Renderer.render(<Greeting />, document.body);
```

**Comment by brainkim** [comment]
Hmmm, so as far as I can tell, the problem is that you’re using JSX in a vanilla JavaScript file. You need to either transpile it or use an alternative. You can, for instance, use createElement directly:
```js
function Greeting({ name = "World" }) {
  return createElement("div", null, "Hello ", name);
}
```
Or you can use something like [htm](https://github.com/developit/htm):
```js
import { createElement } from "https://unpkg.com/@bikeshaving/crank@0.1.6/index.js";
import { Renderer } from 'https://unpkg.com/@bikeshaving/crank@0.1.6/dom.js';
import htm from 'https://unpkg.com/htm?module';
const html = htm.bind(createElement);
function Greeting({ name = "World" }) {
  return html`<div> Hello ${name}</div>`;
}
```

I like transpilation, but these options are available to you. Also check out the docs from [this PR](https://github.com/bikeshaving/crank/pull/18) for more information.

Let me know if this makes sense!

**Comment by Perrishnikov** [comment]
Thanks for your explanation.

**Comment by brainkim** [comment]
Closing for housekeeping purposes. If you still need help feel free to reopen the issue!
