### ISSUE TITLE
Undefined input values are rendered instead of the placeholder text

### ISSUE THREAD

**Issue by ryhinchey** [bikeshaving/crank#125]
This behavior is consistent with the default dom; however, I think it would make sense for Crank to smooth the edges around this like React does.

Crank component demonstrating this: https://codesandbox.io/s/charming-brook-hu2lj?file=/src/index.js

React equivalent: https://codesandbox.io/s/condescending-buck-6nijn?file=/src/App.js

Notice how in the Crank example, `undefined` is rendered in the input whereas with React, the placeholder text is shown

**Comment by brainkim** [comment]
Fixed in 0.2.0
