### ISSUE TITLE
Crank maintainers wisdom required in Twitter discussion

### ISSUE THREAD

**Issue by brucou** [bikeshaving/crank#149]
@brainkim in case you monitor here more often: there is an interesting discussion on twitter addressing crank, and dan has some questions how crank handle concurrency. Would be great if you could chime in:

cf. [here](https://twitter.com/dan_abramov/status/1301682026953793540) and [here](https://twitter.com/dan_abramov/status/1301858469985816577)

**Comment by brainkim** [comment]
Converting to discussion mostly because I want to use that feature more! Thanks for bringing this to my attention, Bruno. Long reply to follow
