### ISSUE TITLE
Suspense component not responding to nested async calls

### ISSUE THREAD

**Issue by mcjazzyfunky** [bikeshaving/crank#154]
Please have a look at the following demo which is using Dyo (if it's not clear what this `useResource` hook is doing, here's the documentation: https://dyo.js.org/hooks.html#useResource):
https://codesandbox.io/s/boring-shadow-2kw63?file=/src/index.js 

Now please have a look at its Crank counterpart:
https://codesandbox.io/s/hardcore-lamarr-by54y?file=/src/index.js

Obviously the Crank version behaves differently as the Dyo version when you click on one of the buttons.
Wouldn't it be much better and more natural if the Crank version behaved the same way as the Dyo version in this little demo?

**Comment by brainkim** [comment]
If you want that behavior you have to get the `Suspense` component itself to rerender when the buttons are pressed.

```jsx
/** @jsx createElement */
import { createElement, Fragment } from '@bikeshaving/crank'
import { renderer } from '@bikeshaving/crank/dom'

async function Fallback({ timeout, children }) {
  await new Promise((resolve) => setTimeout(resolve, timeout))
  return children
}

async function* Suspense({ timeout = 0, fallback, children }) {
  for await ({ timeout = 0, fallback, children } of this) {
    yield <Fallback timeout={timeout}>{fallback}</Fallback>
    yield <Fragment>{children}</Fragment>
  }
}

function getRandomNumberDelayed() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(Math.floor(Math.random() * 10000)), 3000)
  })
}

async function RandomNumber() {
  const randomNumber = await getRandomNumberDelayed()
  return <div>Random number: {randomNumber}</div>
}

function* RandomNumberApp({ onclick }) {
  for ({ onclick } of this) {
    yield (
      <div>
        <RandomNumber />
        <button onclick={onclick}>Load new random number</button>
      </div>
    )
  }
}

function* App() {
  const onclick = () => this.refresh()
  for ({} of this) {
    yield (
      <Suspense fallback={<div>Loading...</div>}>
        <RandomNumberApp onclick={onclick} />
        <hr />
        <RandomNumberApp onclick={onclick} />
      </Suspense>
    )
  }
}

renderer.render(<App />, document.getElementById('root'))
```

https://codesandbox.io/s/empty-mountain-c12ok?file=/src/index.js

It might be a pain, but there’s also Crank’s EventTarget based event system to help you with this kind of logic 🙂

**Comment by mcjazzyfunky** [comment]
Hhhmm, very interesting ... thanks ...

> but there’s also Crank’s EventTarget based event system to help you with this kind of logic 

Yeah, in fact this EventTarget stuff is extremely powerful.
The fact that you can implement a `Suspense` easily in userland is one of the top reamarkable features of Crank IMHO ... it will be still remarkable even if a full-featured `Suspense` implementation will not be easy any longer but still completely possible in userland.
But frankly, the pattern that you are using here will really a bit of a (quote) "pain" for more complex components I guess. By the way, your version is not working properly: If it loads a new random number the other random number should stay the same. But this is not important here, just saying it to emphazise again that some things are not necessarily that easy in Crank as it may look at first sight. But that's not a problem, it's just a nice challenge to evaluate proper usage patterns.
I will close this issue now. Thanks again. I thinks there are some open topics regarding the use of suspense and async components in Crank which are worth a discussion. Guess I will open a corresponding discussion in near future about that.

**Comment by brainkim** [comment]
>  If it loads a new random number the other random number should stay the same.
Ah yeah I guess we’d need to isolate the random number components so thy only fetch on internal refreshes.
