### ISSUE TITLE
Incorrect CodeSandbox link in docs

### ISSUE THREAD

**Issue by joecritch** [bikeshaving/crank#16]
On https://crank.js.org/guides/getting-started, under 'Key Examples', the 'A Simple Component' Codesandbox URL links to a different example.

(Enjoying getting my head around this library. I hope to use it properly soon!)

Update: the link is now 404'ing: https://codesandbox.io/s/a-simple-crank-component-gnknz

**Comment by brainkim** [comment]
Thank you for catching this! Investigating.
