### ISSUE TITLE
jsx-runtime missing

### ISSUE THREAD

**Issue by xdev1** [bikeshaving/crank#237]
It would be really great if Crank had a `jsx-runtime`. 
As hint, please find the Preact counterpart [here](https://github.com/preactjs/preact/blob/master/jsx-runtime/src/index.js).

Would allow the following `tsconfig.json` entries:

```
  "jsx": "react-jsx",
  "jsxImportSource": "@b9g/crank"
```

**Comment by darrylcousins** [comment]
Hi,

I may be off-track here but the similarities strike me. Note that I'm not using Typescript nor is Babel part of my environment.

I'm using [Vite](https://vitejs.dev) and to build jsx with Crank my vite config [esbuild](https://vitejs.dev/config/shared-options.html#esbuild) setting contains the following:

```
export default defineConfig({
  esbuild: {
    jsxFactory: 'createElement',
    jsxFragment: 'Fragment'
  }
})
```
This may be completely unhelpful. My apologies in advance.

Sincerely,
Darryl Cousins

**Comment by xdev1** [comment]
@darrylcousins But you still have to import `createElement` (and `Fragment` if needed) explicitly in each of your component files, don't you? This should not be necessary any longer if you use "jsxImportSource" with a `jsx-runtime`.

**Comment by darrylcousins** [comment]
Hi,

Perhaps not.  The example offered for [esbuild config options](https://vitejs.dev/config/shared-options.html#esbuild) is:

```
export default defineConfig({
  esbuild: {
    jsxInject: `import React from 'react'`
  }
})
```

I assume then (untested) that we could do:

```
export default defineConfig({
  esbuild: {
    jsxFactory: 'createElement',
    jsxFragment: 'Fragment'
    jsxInject: `import {createElement, Fragment} from '@b9g/crank'`
  }
})
```

Hope that helps.

Sincere regards,
Darryl Cousins

**Comment by darrylcousins** [comment]
Hi again,

Update on my previous post. I need not explicitly import `createElement` and `Fragment` in jsx files using the `esbuild` configuration in the last post.

Of course, if I do, it complains that `Identifier 'createElement' has already been declared`.

Kind regards,
Darryl Couins

**Comment by xdev1** [comment]
@darrylcousins Thank you very much, Darryl, for all that info about how JSX can be configured with `Vite`. This was indeed very informative and helpful.
I've not used `Vite` yet, but after your posts above, I'll give it a try ... actually really very nice ...
Nevertheless, as not everybody uses `Vite` and `jsx-runtime`s are some kind of standard now, it would still be great if `Crank` had a `jsx-runtime, I guess` :wink:

**Comment by darrylcousins** [comment]
Hi @xdev1,

Hey, no problem at all. I'm relatively new to nodejs development (python background). I went (sort of) webpack -> brunch -> vite. Most happy with vite. I pass this on to Brian for addressing `jsx-runtime`.

Go well, happy coding,
Darryl Cousins

**Comment by brainkim** [comment]
Added in `0.5`. Sorry for delay!
