### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by crubier** [bikeshaving/crank#25]
First, congrats on the framework, I love the ideas, this is terrific! This is the future for sure, should be react 2.0 really.  

This is actually pretty close to what I designed during my PhD. (Basically views = generators), so as you say this is really something that needed to be “discovered”. 

Now there is only One thing that I am not totally a fond of in the framework, and it is the event listener syntax/pattern. This might be due to a technical impossibility, but I think an API closer to what react does with function handlers passed in `onXXX` attributes on html elements could potentially be better than calling `this.addListener` and adding a big switch on event attributes in there.... However I love how your approach kind of unifies regular state management and reducer-based state management in the same concept. 

I wonder if there could be away to get the best of both worlds!

**Comment by crubier** [comment]
Sorry I just realized this is a duplicate of #10 .. I just wanted to tell my appreciation as well anyway.

**Comment by brainkim** [comment]
I appreciate the kind words! If you want to join the discussion in #10 that’s great too. I’m very receptive to maybe doing both and letting the community decide which is better at this point.
