### ISSUE TITLE
HTML in SVG (via foreignObject & `jsx` function) doesn't render

### ISSUE THREAD

**Issue by canadaduane** [bikeshaving/crank#261]
The following HTML should render a DIV inside an SVG document, but doesn't seem to be visible when built with `jsx` (It works in a plain HTML page). I tried to detect if the rendered jsx DIV has an xhtml or svg namespace, and it seems to correctly have an xhtml namespace, so I'm not sure why it wouldn't be rendering?

```js
    yield jsx`<svg
      viewBox="0 0 ${w} ${h}"
      xmlns="http://www.w3.org/2000/svg"
    >
      <foreignObject x="10" y="10" width="100" height="150">
        ${html`
          <div xmlns="http://www.w3.org/1999/xhtml">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis
            mollis mi ut ultricies. Nullam magna ipsum, porta vel dui convallis,
            rutrum imperdiet eros. Aliquam erat volutpat.
          </div>
        `}
      </foreignObject>
    </svg>`
```

**Comment by canadaduane** [comment]
Sorry for the confusion. I've aliased "svg" and "html" to "jsx" simply because VSCode has a plugin that naturally syntax highlights the inner tagged template string correctly if I do this. (https://github.com/mjbvz/vscode-lit-html)

So `jsx` === `html` === `svg` here (and I meant to replace `html` with `jsx` to avoid the confusion!)

**Comment by brainkim1** [comment]
@canadaduane That’s a great shim file but I cannot endorse the naming. Thank you so much!

I can’t close issues right now, so uhhhh, nice to see what it’s like on the visitor side.

**Comment by canadaduane** [comment]
Oh, are you saying if I change the name "html" to "jsx" it will somehow just work?

Oct 9, 2023 7:30:12 PM brainkim1 ***@***.***>:

**Comment by canadaduane** [comment]
Oh my! This is strange but interesting. This works:

```js
import { jsx } from "@b9g/crank/standalone";

const html = jsx;
const svg = jsx;
```

but this does not!

```js
import { jsx } from "@b9g/crank/standalone";

export { jsx as html, jsx as svg }
```

Thanks for your patience.
