### ISSUE TITLE
Can't express HTML entities in jsx template strings, e.g. &nbsp; or &#8203;

### ISSUE THREAD

**Issue by canadaduane** [bikeshaving/crank#262]
When writing HTML entities in jsx template strings, the strings are preserved as-is rather than expressed as the expected HTML entity.

For example, `&nbsp;` becomes the string `&nbsp;` rather than ` `.

**Comment by darrylcousins** [comment]
Hi Duane,

An example would be helpful. Usually I can write

`<span>&nbsp;</span>`

and the entity will be respected. However, if required, a simple workaround is to use;

`{ "  " }`

for the same result.

Hope that helps.
Ngā mihi, Darryl

**Comment by canadaduane** [comment]
Here's an example:

```html
<!DOCTYPE html>
<script type="importmap">
  {
    "imports": {
      "@b9g/crank/dom": "https://cdn.jsdelivr.net/npm/@b9g/crank/dom/+esm",
      "@b9g/crank/standalone": "https://cdn.jsdelivr.net/npm/@b9g/crank/standalone/+esm"
    }
  }
</script>
<script type="module">
  import { renderer } from "@b9g/crank/dom";
  import { jsx } from "@b9g/crank/standalone";

  function Component() {
    return jsx`Hello&nbsp;there`;
  }

  renderer.render(jsx`<${Component} />`, document.body);
</script>
```

**Comment by darrylcousins** [comment]
Hi Duane,

Thanks for that. I've only used crank with transpiled jsx transform and never used the [tagged template function](https://crank.js.org/guides/jsx-template-tag/).

Some workarounds here: [JSX Gotchas](https://shripadk.github.io/react/docs/jsx-gotchas.html) for html entities.

Hope that helps.
Darryl

**Comment by canadaduane** [comment]
> Some workarounds here: [JSX Gotchas](https://shripadk.github.io/react/docs/jsx-gotchas.html) for html entities.
> 
> Hope that helps. Darryl

I didn't realize this uses the same functionality as React's JSX tagged template function, so I'll go there for docs in future. Good to know, thanks!

**Comment by brainkim1** [comment]
Hello. This is Brian Kim, posting on my alternate account while I am locked out of GitHub.

I apologize about the poor documentation and poor developer experience related to the `jsx` template tag function! At a high-level, the template tag parser is dumb / simple, and some of the intricacies of HTML were left out for the sake of bundle size and maintainer sanity. HTML entities can be expressed using the special `Raw` element tag:

```js
import {Raw} from "@b9g/crank/standalone"; 
/* ... */

  return jsx`<${Raw} value="&copy;" />`;

```

You can also use `innerHTML` or other more dangerous tricks if you know what you are doing.

Thank you for opening this issue and again, I apologize for the shitty DX. The `jsx` template tag can do with a lot more helpful error messages. In the meantime, I encourage you to read the source code to see how it is implemented here:

https://github.com/bikeshaving/crank/blob/master/src/jsx-tag.ts

I hope you have a productive Monday, if you are not celebrating the federal holiday.

**Comment by darrylcousins** [comment]
Thanks Brian,

Darn, I should have thought of the Raw tag when pondering Duane's problem. My preference is to just use unicode everywhere.  I haven't used Raw anywhere in my code. I'm sure I found a use for it at some point and then later I must have found another way to do whatever it was I was trying to do. I was pretty sure that `grep -r Raw src` would have turned something up but it didn't.

Regards,
Darryl

P.S. For a one-man band and a wonderful system - "the poor documentation and poor developer experience" is hardly a fair description. I find the documentation more than adequate (sure - aim of exceptional, but hey it's a real world) and the developer experience ... dare I say it: fun.

P.P.S. Sorry you're locked out of GitHub. Were you naughty? (No reply required) :-(

**Comment by brainkim1** [comment]
@darrylcousins 
> My preference is to just use unicode everywhere.

Yes, thank you! I agree with this wholeheartedly! Prefer unicode to HTML entities, whether that is via JavaScript string literals `"©"` or character escapes `\u00A9`. The one confusing detail is that JSX text does not adhere to the same grammar as string literals, so you will likely need to punch a hole in the template literal.

```js
yield jsx`<p>${"\u00A9"}</p>`;
```

With regard to supporting HTML entities in the `jsx` template tag function: I had no idea the JSX specification supported HTML entities in a limited and confusing way, and not only that, but just a under-specified subset (see https://github.com/microsoft/TypeScript/issues/47030). I highly recommend against mixing HTML entities with JSX, and would be opposed to supporting this in the template tag. Of course, we don’t have a custom JSX syntax parser yet, and probably never will, so HTML entities may be supported.

This is probably very confusing for people not familiar with the intricacies JavaScript, JSX, tagged template literals, string literals, etc, and for that, I apologize on behalf of software engineers everywhere.

**Comment by brainkim** [comment]
Closing this issue as unactionable because I don’t really want to add HTML entities to jsx template tags. Please feel free to continue commenting!
