### ISSUE TITLE
When does a render get mounted?

### ISSUE THREAD

**Issue by canadaduane** [bikeshaving/crank#265]
The docs point towards there being a React-y equivalent of "componentDidMount", but I'm having trouble replicating what (I think) the docs are describing:

> componentWillMount and componentDidMount
>
> Setup code for components can be written at the top of generator components. It will not execute until the component is mounted in the tree.

```html
<!DOCTYPE html>
<script type="importmap">
  {
    "imports": {
      "@b9g/crank/dom": "https://cdn.jsdelivr.net/npm/@b9g/crank@0.5.4/dom/+esm",
      "@b9g/crank/standalone": "https://cdn.jsdelivr.net/npm/@b9g/crank@0.5.4/standalone/+esm"
    }
  }
</script>
<script type="module">
  import { renderer } from "@b9g/crank/dom";
  import { jsx, createElement } from "@b9g/crank/standalone";

  async function* App() {
    for await (const {} of this) {
      const el = yield jsx`<div>Hello</div>`;
      console.log("el", el, el.parentElement);  // "el", <div>, null
    }
  }

  renderer.render(createElement(App), document.body);
</script>
```

How can I know (within the `App` component) the moment "el" has `parentElement` (i.e. "isConnected" to the document.body)?

Edit: I think this issue also affects the `FocusingInput` example in the docs:

```js
  function* FocusingInput(props) {
    for (props of this) {
      this.schedule((input) => input.focus());
      yield createElement("input", { ...props });
    }
  }
```

AFAICT, the input does not receive focus.

**Comment by darrylcousins** [comment]
Hi Duane (and Brian),

Yes, I had trouble figuring this out, my solution works but I'm looking forward to Brian's input.

I have a wrapper component that wraps any other component and makes it collapsible. My problem (and it was a year or so ago) was figuring the height of the component which isn't available until it was rendered in the dom. Most of time this wasn't a problem, but with adding window.resize events and other user activity my collapsible component would break because it was refreshing or other dom components were mutating. The solution I have below has proved to be robust, even if it is not the best solution - note the problem with async components.

```javascript
<!DOCTYPE html>
<script type="importmap">
  {
    "imports": {
      "@b9g/crank/dom": "https://cdn.jsdelivr.net/npm/@b9g/crank/dom/+esm",
      "@b9g/crank/standalone": "https://cdn.jsdelivr.net/npm/@b9g/crank/standalone/+esm"
    }
  }
</script>
<script type="module">
  import { renderer } from "@b9g/crank/dom";
  import { jsx, createElement } from "@b9g/crank/standalone";

  /*
   * @function sleepUntil
   * Wait for element to be rendered
   * From https://levelup.gitconnected.com/javascript-wait-until-something-happens-or-timeout-82636839ea93
   *
   */
  export const sleepUntil = async (f, timeoutMs) => {
    return new Promise((resolve, reject) => {
      let timeWas = new Date();
      let wait = setInterval(function() {
        if (f()) {
          clearInterval(wait);
          resolve();
        } else if (new Date() - timeWas > timeoutMs) { // Timeout
          clearInterval(wait);
          reject();
        }
        }, 20);
      });
  };

  async function* App({ id, collapsed, ...props }) {

    for await (const {id, collapsed: newCollapsed, ...props} of this) {
      let el = yield jsx`<div id="${id}">Hello</div>`;

      // wait until the element has rendered, note that this fails if the component
      // is an async generator component and I don't know how to fix it
      await sleepUntil(() => document.querySelector(`#${id}`), 1000);

      el = document.querySelector(`#${id}`);
      if (el) console.log("el", el, el.parentElement);  // "el", <div>, <body>...</body>

      /* My collapse element code, unimportant here
      if (el) {
        const fn = newCollapsed ? collapseElement : transitionElementHeight;
        fn(el);
      };
      collapsed = newCollapsed;
      */
    }
  }

  renderer.render(jsx`<${App} id="myDiv" />`, document.body);
</script>
```

Hope that's worth something.

Ngā mihi,
Darryl

**Comment by canadaduane** [comment]
I've found a bit of a workaround here, although I'm not sure if I should be proud of it.

```html
<!DOCTYPE html>
<script type="importmap">
  {
    "imports": {
      "@b9g/crank/dom": "https://cdn.jsdelivr.net/npm/@b9g/crank@0.5.4/dom/+esm",
      "@b9g/crank/standalone": "https://cdn.jsdelivr.net/npm/@b9g/crank@0.5.4/standalone/+esm"
    }
  }
</script>
<style>
  body {
    color: white;
    text-align: center;
    background-color: rgb(43, 7, 77);
  }
</style>
<script type="module">
  import { renderer } from "@b9g/crank/dom";
  import { jsx, createElement } from "@b9g/crank/standalone";

  function dispatchEventDownTree(node, event) {
    // Dispatch event to the current node
    node.dispatchEvent(event);
    for (let child of node.childNodes || []) {
      // Recursively dispatch the event down the tree
      dispatchEventDownTree(child, event);
    }
  }

  const originalAppendChild = Node.prototype.appendChild;

  Node.prototype.appendChild = function (newNode) {
    const newNodeIsConnected = newNode.isConnected;
    const result = originalAppendChild.apply(this, arguments);
    if (
      this.isConnected &&
      !newNodeIsConnected &&
      newNode.nodeType === Node.ELEMENT_NODE
    ) {
      dispatchEventDownTree(
        this,
        new CustomEvent("attached", { bubbles: false, detail: { root: this } })
      );
    }
    return result;
  };

  function* FocusingInput(props) {
    this.schedule((input) => {
      input.addEventListener("attached", (...args) => {
        input.focus();
      });
    });
    for (props of this) {
      yield createElement("input", { ...props });
    }
  }

  async function* App() {
    for await (const {} of this) {
      const el = yield jsx`<div>Hello: <${FocusingInput} value="test" /></div>`;
    }
  }

  renderer.render(createElement(App), document.body);
</script>
```

Basically, I modify the built-in `appendChild` function to notify every node in the subtree whenever the top-level element is connected to a node that is already connected to the DOM.

The upside is that it happens each time, at the moment when it should occur. Events are great that way.

The downside is that this is a modification of a core Node.prototype function, which makes me feel like there should be a better way--and I've modified something that will affect everything, whether crank-related or not.

**Comment by brainkim1** [comment]
Can you try `this.flush(() => {})`? Same API as `this.schedule()` except it fires after the DOM nodes are in the document. It’s a weird thing but `this.flush(() => {})` is usually what you are looking for. The `schedule(() => {})` callback fires before the DOM nodes are inserted for some reasons that I don’t remember right now, but I believe to be very good reasons. Probably something to do with the future API. I dunno.

Thank you for your patience as I try to recover my accounts.

**Comment by brainkim** [comment]
My lock-out alt is correct here! The `this.flush()` method is the canonical way to run code after a component has fully rendered and inserted elements into the DOM.

Closing for housekeeping purposes.
