### ISSUE TITLE
Landing page `Definition` component breaks if searched word is not found

### ISSUE THREAD

**Issue by neodon** [bikeshaving/crank#276]
Just came across this framework and about to try it on a project.

I wanted to make you aware of a small issue with the demos on your landing page. I impulsively typed a bunch of random letters to test the `Definition` component under `Reason #3`. This triggered an error message and the component could not recover without a page refresh.

Again really not a big deal. I figured maybe you normally test the page out with, like, real words, and my case is rare. 😀

<img width="881" alt="chrome_pGNYHT0Ic2" src="https://github.com/bikeshaving/crank/assets/82944/ffa3dc9e-2303-4235-8a21-b4417e4bfa31">

**Comment by brainkim** [comment]
Fixed! Thanks for catching that!
