### ISSUE TITLE
Website Content Overflow

### ISSUE THREAD

**Issue by jbest84** [bikeshaving/crank#278]
If your browser is set to a larger font size (mine is 20px), the left nav/sidebar will overlap into the main content.

It appears at larger screen sizes the sidebar width is 20rem. The main element  however has a `margin-left: 320px`

https://github.com/bikeshaving/crank/blob/master/website/src/components/sidebar.ts#L85

If this is changed to a `margin-left: 20rem;` to match, it works fine.

## Before
![crank_before](https://github.com/user-attachments/assets/84cc8b7a-8e93-4879-bc28-1713821e0d44)

## After
![crank_after](https://github.com/user-attachments/assets/6a0d7d8b-23fa-45d9-8b72-ec9255990763)

**Comment by brainkim** [comment]
Thanks for opening the issue! Sorry for the delay.
