### ISSUE TITLE
Examples!

### ISSUE THREAD

**Issue by brainkim** [bikeshaving/crank#38]
I see your comments and appreciate all the design feedback, but I must admit, writing long technical responses can be both intellectually and emotionally draining. Know that I see you and I will get back to you ASAP about my thoughts on all of this stuff.

One thing that I love more than anything is seeing examples! Have you made Snake or Tetris? Let me know in this issue 🙆‍♀️

**Comment by shirakaba** [comment]
I've started making a spinning Web Browser in Crank Native:

https://play.nativescript.org/?template=play-react&id=LB4qRS&v=4

It accesses native iOS methods to inject some JS into the webpage to make things, uh, spin.

![IMG_9619](https://user-images.githubusercontent.com/14055146/79693167-05dc8c80-8261-11ea-8d9e-31453d7cafbb.PNG)

**Comment by shirakaba** [comment]
Built an iOS SpriteKit game launcher in Crank Native:

https://play.nativescript.org/?template=play-react&id=ptkGyA&v=8

![IMG_9620](https://user-images.githubusercontent.com/14055146/79693871-0bd46c80-8265-11ea-9e06-f1a53588ff27.PNG)

![IMG_9624](https://user-images.githubusercontent.com/14055146/79693876-10992080-8265-11ea-9c83-a8a90ebd239f.PNG)

**Comment by ryhinchey** [comment]
I came across this on Twitter:


https://codesandbox.io/embed/crankjs-final-form-jk3q9?file=/src/index.js&codemirror=1


https://twitter.com/erikras/status/1251584285192138753?s=21

**Comment by btheado** [comment]
I copied the code examples from https://crank.js.org/guides/components to https://observablehq.com/@btheado/crank-js and translated them to use [htm](https://github.com/developit/htm). All the examples are live-editable and runnable.

When I first read about crank.js the other day, I was reminded of the way observablehq uses generators and async generators. I haven't yet compare/contrasted them, so I don't know how similar they are. I thought I'd play with crank on observable with the eventual goal of finding out. The above page is the result.

**Comment by ryhinchey** [comment]
I just put this together using the undocumented `this.set` and `this.get` (kind of like React contexts) https://codesandbox.io/s/lucid-bash-nh846?file=/src/index.js

```js
/** @jsx createElement */
import { createElement, Fragment } from "@bikeshaving/crank";
import { renderer } from "@bikeshaving/crank/dom";

function Avatar() {
  const user = this.get("user");
  return <img alt={`${user.first_name} ${user.last_name}`} src={user.avatar} />;
}

function User() {
  const user = this.get("user");

  return (
    user && (
      <div>
        <p>{user.first_name}</p>
        <Avatar image={user.avatar} />
      </div>
    )
  );
}
async function* App() {
  try {
    let value = "";

    const onChange = e => {
      value = e.target.value;
      this.refresh();
    };

    const onSubmit = async (e) => {
      e.preventDefault();
      const response = await fetch(`https://reqres.in/api/users/${value}`);
      const user = await response.json();
      this.set("user", user.data);
      this.refresh();
    };

    for await (let _ of this) {
      yield (
        <Fragment>
          <form onsubmit={onSubmit}>
            <label for="userSelector">Select a User Number (1 - 10)</label>
            <input
              value={value}
              onchange={onChange}
              id="userSelector"
              type="number"
              max="10"
              min="1"
            />
            <button type="submit">Get new User</button>
          </form>
          <p>Selected Number: {value}</p>
          <User />
        </Fragment>
      );
    }
  } catch (error) {
    return <h1>error getting data </h1>;
  }
}

renderer.render(<App />, document.body);

```

The `App` component is an async generator and I'm using `for await (let _ of this)` for my UI to respond to changes.  I'm not using any props and am getting an eslint warning for unused variable `_`.    @brainkim What's the suggestion here?  I'm pretty sure I need to use the `for await of`.

Also - `this.set` and `this.get` are great to have in the framework (Although I think we might want to move them to something like `this.proisions.get` or `this.context.get`)

**Comment by brainkim** [comment]
Here‘s the XState calculator example in Crank: https://codesandbox.io/s/xstate-calculator-with-crankjs-u9r0f?file=/src/index.tsx

I see that there could probably be some kinda of plugin created which refreshes on transition automatically I just don’t know what it should look like yet. In the meantime it just works with a couple helper functions and an explicit refresh call.
