### ISSUE TITLE
seeking feedback - crank testing library 

### ISSUE THREAD

**Issue by ryhinchey** [bikeshaving/crank#40]
Throwing this out there to get some feedback.  

I put together an initial version of `crank-testing-library` and have it working!  Kudos to the testing library team for making it simple to integrate with new frameworks.

Here's the library:
https://github.com/ryhinchey/crank-testing-library

And an example:
https://github.com/ryhinchey/crank-testing-library-example

**Comment by brainkim** [comment]
This looks dope! I’ve been doing really icky tests with JSDOM and Jest so I may want to use DOM-testing-library in the future!

One other thing I think we should figure out is how testing works with events/promises/async updates. We could, for instance, a mock context so events can be triggered? Lots of room for innovation.

Overall, thanks for the effort, and I’ll make sure to give this a go! Although I’ll be honest I never wrote that many tests for React stuff.

**Comment by ryhinchey** [comment]
Cool - I’m going to put together some examples with this that I think might be helpful to explore.

I’ll close this issue and open up others related to testing as I come across them.
