### ISSUE TITLE
Question regarding components whose side effects depend on (possibly changing) prop values

### ISSUE THREAD

**Issue by mcjazzyfunky** [bikeshaving/crank#43]
Normally the Github issue tracker is not necessarily there to ask questions about certain implementation cases. I hope you do not mind if I do nonetheless :-)

Please have a look at the following React demo:
https://codesandbox.io/s/frosty-kowalevski-4qp51?file=/src/index.js

The implementation of component "Ticker" is quite trivial in React
(normally I would use a "useInterval" custom hook for this, but this is not important here...)

What is the best way to implemenent that "Ticker" component in Crank.js?

Please find here a NOT YET WORKING Crank.js version of the demo:
https://codesandbox.io/s/tender-greider-qto05?file=/src/index.js

Many many thanks in advance.

**Comment by MattyBalaam** [comment]
Out of my own interest in how crankjs works I’ve taken a look.

where you are going wrong is using a while loop in your `Ticker` component. Take a look at the `Counter` example here: https://crank.js.org/guides/components

You will need to replace your `while(true)`  with `for ({ milliseconds } of this)`

**Comment by ryhinchey** [comment]
yah this should do the trick:

```js
/** @jsx createElement */
import { createElement } from '@bikeshaving/crank'
import { renderer } from '@bikeshaving/crank/dom'

// Bug: Component Ticker is obviously NOT working yet!
function* Ticker({ milliseconds = 1000 }) {
  let tickCount = 0

  for ({milliseconds} of this) {
    yield (
      <div>
        Number of ticks: {tickCount} (
          => next change in {milliseconds} ms)
      </div>
    )
    tickCount += 1;
  }
}

function* App() {
  let milliseconds = 1000

  const decreaseMilliseconds = () => {
    milliseconds -= 50
    this.refresh()
  }

  while (true) {
    if (milliseconds > 100) {
      setTimeout(decreaseMilliseconds, 1000)
    } else {
      setTimeout(() => this.refresh(), milliseconds)
    }

    yield (
      <div>
      Tick interval:
      <span> { milliseconds } ms</span>
      <br/>
      <Ticker milliseconds={milliseconds}/>
      </div>
    )
  }
}

renderer.render(<App/>, document.body)

```

**Comment by mcjazzyfunky** [comment]
@ryhinchey Thanks you very much for your demo, but frankly it is not  really 100% working:
https://codesandbox.io/s/mystifying-roentgen-qwt6j?file=/src/index.js

The update of that "Number of ticks" value should always  happen faster (until the tick interval is 100 ms):
First change should be after 1000ms, second update after additional 950ms, third update after additional 900ms etc. ... and in the end it should increment each 100 ms.
In your demo the "Number of ticks" value increases each second until the "Number of ticks" value is 18, after that it will be incremented each 100 ms.
Also be aware that the `Ticker` component should be stateful and increment the tick counter on its own.
Thanks a lot for your help.

**Comment by MattyBalaam** [comment]
You might notice you are using a 'magic number' on line 29 rather than a variable.

**Comment by mcjazzyfunky** [comment]
@MattyBalaam What do you mean by "magic number"? Actually, that constant value `1000` in line 29 is exactly what I want (each second the tick interval shall be decreased by 50 ms, until the tick interval is 100 ms).

**Comment by mcjazzyfunky** [comment]
@ryhinchey Frankly, that's not really what I want: Component `Ticker` SHALL be stateful/effectful, that's the whole point of that demo.  Component `Ticker` is of the pattern "a stateful component with side effects that depend on possibly changing prop values", something like this is currently not to be found in the Crank.js documentation as far as I know.

**Comment by monodop** [comment]
I think I have a working equivalent:
https://codesandbox.io/s/red-fire-j8v6p?file=/src/index.js

```jsx
/** @jsx createElement */
import { createElement } from "@bikeshaving/crank";
import { renderer } from "@bikeshaving/crank/dom";

function createWasChanged(initial) {
  let current = initial;
  return test => {
    if (current !== test) {
      current = test;
      return true;
    }
    return false;
  };
}

function* Ticker({ milliseconds = 1000 }) {
  let tickCount = 0;
  let msWasChanged = createWasChanged(milliseconds);
  let timer = null;

  const onTick = () => {
    tickCount++;
    this.refresh();
  };

  const clearTimer = () => {
    if (timer) {
      clearInterval(timer);
      timer = null;
    }
  };

  const updateTimer = ms => {
    clearTimer();
    timer = setInterval(onTick, ms);
  };

  updateTimer(milliseconds);

  try {
    for ({ milliseconds } of this) {
      if (msWasChanged(milliseconds)) {
        updateTimer(milliseconds);
      }
      yield (
        <div>
          Number of ticks: {tickCount} ( => next change in {milliseconds} ms)
        </div>
      );
    }
  } finally {
    clearTimer();
  }
}

function* App() {
  let milliseconds = 1000;
  let msWasChanged = createWasChanged(0);
  let timer = null;

  const decreaseMilliseconds = () => {
    if (milliseconds <= 100) return;

    milliseconds -= 50;
    this.refresh();
  };

  try {
    while (true) {
      if (msWasChanged(milliseconds)) {
        timer = setTimeout(decreaseMilliseconds, 1000);
      }

      yield (
        <div>
          Tick interval:
          <span> {milliseconds} ms</span>
          <br />
          <Ticker milliseconds={milliseconds} />
        </div>
      );
    }
  } finally {
    if (timer) clearTimeout(timer);
  }
}

renderer.render(<App />, document.body);
```

**Comment by monodop** [comment]
I also made another version with some helper functions similar to React hooks. I know we shouldn't be focusing too much on emulating react's paradigms, but this looks a little cleaner to me:
https://codesandbox.io/s/wizardly-wind-m4ocp?file=/src/index.js

```jsx
/** @jsx createElement */
import { createElement } from "@bikeshaving/crank";
import { renderer } from "@bikeshaving/crank/dom";

function createWasChanged(items) {
  let current = items;
  return items => {
    let equal = true;
    if (current === undefined) {
      equal = false;
    } else if (current.length !== items.length) {
      equal = false;
    } else {
      for (let i = 0; i < current.length; i++) {
        if (current[i] !== items[i]) {
          equal = false;
          break;
        }
      }
    }

    current = items;
    return !equal;
  };
}

function createUseEffect() {
  let wasChanged = createWasChanged();
  let cleanup = undefined;
  const cleanupFunc = () => {
    if (typeof cleanup === "function") cleanup();
  };
  let effect = (setup, items) => {
    if (wasChanged(items)) {
      cleanupFunc();
      cleanup = setup();
    }
  };
  return [effect, cleanupFunc];
}

function* Ticker({ milliseconds = 1000 }) {
  let tickCount = 0;
  let [msEffect, msEffectCleanup] = createUseEffect();

  try {
    for ({ milliseconds } of this) {
      msEffect(() => {
        let timer = setInterval(() => {
          tickCount++;
          this.refresh();
        }, milliseconds);
        return () => {
          clearInterval(timer);
        };
      }, [milliseconds]);
      yield (
        <div>
          Number of ticks: {tickCount} ( => next change in {milliseconds} ms)
        </div>
      );
    }
  } finally {
    msEffectCleanup();
  }
}

function* App() {
  let milliseconds = 1000;
  let [msEffect, msEffectCleanup] = createUseEffect();

  try {
    while (true) {
      msEffect(() => {
        let timer = setTimeout(() => {
          if (milliseconds <= 100) return;

          milliseconds -= 50;
          this.refresh();
        }, 1000);
        return () => {
          clearTimeout(timer);
        };
      }, [milliseconds]);

      yield (
        <div>
          Tick interval:
          <span> {milliseconds} ms</span>
          <br />
          <Ticker milliseconds={milliseconds} />
        </div>
      );
    }
  } finally {
    msEffectCleanup();
  }
}

renderer.render(<App />, document.body);
```

**Comment by mcjazzyfunky** [comment]
@monodop Thank you very much, Harrison

Good job, not exact 100% correct yet (for example milliseconds default prop value is not working in general and the ticker starts to count a bit late) but this is not really that important.

Actually my question at the top of this issue was all about to show that there are some aspects of UI programming (where React has already more or less easy answers how to implement) that are not yet addressed in the Crank.js documentation sufficiently (and maybe not even in the API), and I think the above demo is a good example use case for that.

Have a look for example on those two simple React component implementations: 

```jsx
function Ticker({ label = 'Number of ticks', milliseconds = 1000 }) {
  const [count, setCount] = useState(0)

  useInterval(() => setCount(it => it + 1), milliseconds)

  return <div>{label}: {count} (will be increased in {milliseconds} ms)</div>
}

```

```jsx
function Demo() {
  const
    [mouseX, mouseY] = useMousePosition(),
    time = useTime()

  return (
    <div>
      <div>Current time: {time}</div>
      <div>Mouse position: {mouseX}x{mouseY}</div>
    </div>
  )  
}
```

Even with these quite small components you can see some really nice features of React's hook API:

- Syntax is quite concise
- The use of default props is extremely easy
- Cross cutting concerns and often used general logic can easily be handled by custom hook functions (=> higher code reusability)
- Abstracting side effects (including state managment) can easily be handled by custom hook functions
- The React hook API allows to use immutable data and constant variables at least quite often (of course refs for example are an exception)

None of the topics in this list has been addressed sufficiently by Crank.js yet in my opinion (at least not in the documentation).
I really wonder why nobody has ever mentioned this - maybe I am just missing something completely ....

@brainkim This issue was just to show that there may be still some common use cases which have possibly not yet addressed by the Crank.js API or documentation ... feel free to close this issue whenever you like ... thanks .... and also many thanks in general for this really interesting library ...

**Comment by monodop** [comment]
I'm guessing part of the problem is that the library is so new that many patterns haven't really been invented yet. There's still a lot of room to experiment with different types of apis and approaches. It might be nice to have some examples to get people started, but they probably shouldn't be presented as The Way To Do It™.

One thing that I've been struggling with is figuring out how to cleanly abstract logic. The two approaches I've found so far are:

- higher order components, though I've been having a really difficult time figuring out how to get this working properly, especially with typescript. It'd be nice to have a type that represents any component with TProps that I can just stick into my function. And I'm not sure if I have to worry too much in my logic about if the wrapped component is a generator/iterator/async/etc. An example around this would be really nice to have.
- something like the createUseEffect described above, though it doesn't really handle cleanup well.

But maybe there's something else we can do, maybe something that utilizes the event system?

**Comment by brainkim** [comment]
@mcjazzyfunky Just catching up on this issue. Here’s what you’re looking for:

https://codesandbox.io/s/gallant-clarke-hs50l?file=/src/index.js
```ts
function* Ticker({ ms = 1000 }) {
  let count = 0;
  let nextMs = 1000;
  const tick = () => {
    count++;
    this.refresh();
  };

  let id = setInterval(tick, nextMs);
  for ({ ms: nextMs = 1000 } of this) {
    if (ms !== nextMs) {
      clearInterval(id);
      id = setInterval(tick, nextMs);
    }
    yield (
      <div>
        Number of ticks: {count} ( => next change in {ms} ms)
      </div>
    );
    ms = nextMs;
  }
}

function* App() {
  let ms = 1000;
  const change = () => {
    if (ms <= 100) {
      return;
    }
    ms -= 50;
    this.refresh();
    setTimeout(change, 1000);
  };

  setTimeout(change, 1000);
  while (true) {
    yield (
      <div>
        Tick interval:
        <span> {ms} ms</span>
        <br />
        <Ticker ms={ms} />
      </div>
    );
  }
}

renderer.render(<App />, document.body);
```
I haven’t been able to read through everyone’s solutions but this is how I would do it. One thing about Crank is that you can do side-effects right in the main loop and not have to feel guilty about it 😇. I know you’ve always wanted to put side-effects in your React render methods and it’s possible with Crank because it’s executionally transparent.

**Comment by brainkim** [comment]
@mcjazzyfunky These kinds of issues are fun. If you have any other issues like “How do I do X in Crank,” I have tons of experience with generators and probably know the cleanest way to do it, so please open more issues!

**Comment by BrandonNoad** [comment]
I came up with something similar to @brainkim 

https://codesandbox.io/s/wispy-sun-ri4y5?file=/src/index.js:0-1319

```
/** @jsx createElement */
import { createElement } from "@bikeshaving/crank";
import { renderer } from "@bikeshaving/crank/dom";

function* Ticker() {
  const context = this;
  let currentDelay = 1000;
  let tickCount = 0;
  let intervalId;

  const setNewInterval = delay => {
    clearInterval(intervalId);

    intervalId = setInterval(() => {
      tickCount += 1;
      context.refresh();
    }, delay);
  };

  try {
    for (const { milliseconds } of context) {
      if (milliseconds !== undefined && milliseconds !== currentDelay) {
        currentDelay = milliseconds;
        setNewInterval(currentDelay);
      }

      yield (
        <div>
          Number of ticks: {tickCount} ( => next change in {currentDelay} ms)
        </div>
      );
    }
  } finally {
    clearInterval(intervalId);
  }
}

function* App() {
  const context = this;
  let milliseconds = 1000;

  const setNewTimeout = () => {
    if (milliseconds <= 100) {
      return;
    }

    setTimeout(() => {
      milliseconds -= 50;

      context.refresh();
    }, 1000);
  };

  while (true) {
    setNewTimeout();

    yield (
      <div>
        Tick interval:
        <span> {milliseconds} ms</span>
        <br />
        <Ticker milliseconds={milliseconds} />
      </div>
    );
  }
}

renderer.render(<App />, document.body);
```

**Comment by monodop** [comment]
@brainkim Your version looks very neat and concise for this example, but I'm worried that this approach won't look so nice on a larger or more complicated problem as parts of it are spread into different parts of the same function. I wonder what can be done to extract various concerns out into separate pieces that can then be assembled back into the finished solution.

**Comment by mcjazzyfunky** [comment]
Thanks a lot, guys, for all your feedback.
Maybe its not the best way to make friends if I go on writing all that annoying stuff 😄, nevertheless still none of the implementations is really working 100% correct, in each implementation at least one of the following things are not working properly:

- Both millisecond outputs must show the same value (= be in sync)
- After one second "Tick interval" should show "950 ms" and "Number of ticks" should show "1"
- `clearInterval` should be called on unmount

Like said, it's not really important whether the implementations above are 98% fine or 100% fine.
The reason why I'm annoying you with saying that it's still not working perfectly is that it shows quite well that Crank.js really needs something similar to React hooks to make the component implementations more concise and more declarative and to make code and logic in general more reusable.

Again: Just compare the Crank.js implementations above with the following (already mentioned) React implementation:

```jsx
function Ticker({ label = 'Number of ticks', milliseconds = 1000 }) {
  const [count, setCount] = useState(0)

  useInterval(() => setCount(it => it + 1), milliseconds)

  return <div>{label}: {count} (will be increased in {milliseconds} ms)</div>
}
```

Frankly I have no idea how a Crank.js counterpart of React hooks could look like (espacially it would be interesting how the return values of those hook counterparts would look like).

---

A bit off-topic: Would be really great if that Crank.js-like generator approach could be used somehow to implement custom elements ("web components").
For example if the third parameter of the `component` function in the following demo could be replaced by a generator function in a Crank.js way (the demo uses a toy library that's based on a factory pattern .... just for fun ... don't take that too serious):
https://codesandbox.io/s/amazing-wiles-biibp?file=/src/index.js

**Comment by brainkim** [comment]
Updated the example to meet your spec:
https://codesandbox.io/s/gallant-clarke-hs50l?file=/src/index.js

```jsx
/** @jsx createElement */
import { createElement } from "@bikeshaving/crank";
import { renderer } from "@bikeshaving/crank/dom";

function* Ticker({ ms = 1000 }) {
  let count = 0;
  let nextMs = 1000;
  const tick = () => {
    count++;
    this.refresh();
  };

  let id = setInterval(tick, nextMs);
  try {
    for ({ ms: nextMs = 1000 } of this) {
      if (ms !== nextMs) {
        clearInterval(id);
        id = setInterval(tick, nextMs);
      }
      yield (
        <div>
          Number of ticks: {count} (=> next change in {nextMs} ms)
        </div>
      );
      ms = nextMs;
    }
  } finally {
    clearInterval(id);
  }
}

function* App() {
  let ms = 1000;
  let id;
  const change = () => {
    if (ms <= 100) {
      return;
    }
    ms -= 50;
    this.refresh();
    id = setTimeout(change, 1000);
  };

  id = setTimeout(change, 1000);
  try {
    while (true) {
      yield (
        <div>
          Tick interval:
          <span> {ms} ms</span>
          <br />
          <Ticker ms={ms} />
        </div>
      );
    }
  } finally {
    clearTimeout(id);
  }
}

renderer.render(<App />, document.body);
```

You can use try/finally to insert cleanup logic. I agree that abstracting this sort of logic can be cool, and I’m curious what that would look like. However, I guarantee you the most optimal solution is not hooks and encourage you to experiment (see #36 for more discussion). One thing I do want to do is define more methods on the context like setInterval/setTimeout which teardown automatically (see #35 by @jasonmatthewdev), but that might not completely solve the valid points y’all raise; how do we abstract some shared logic. Maybe a plugin system. Maybe taking a look at async iterators and creating combinator functions to work with them more easily. I have some ideas but I’d like to hear suggestions.

**Comment by brainkim** [comment]
@mcjazzyfunky I encourage you to open another issue for web components I’d like to hear more thoughts on that and have wanted to do something similar.

**Comment by mcjazzyfunky** [comment]
Okay, so thanks to everyone for the very helpful feedback.
I will close this issue now - nevertheless, if someone still likes to add some additional comments: Feel free to do so ;-)
