### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by cpryland** [bikeshaving/crank#53]
In the *JSX, Elements and Renderers* documentation, section *Element Diffing*:

>Crank uses the same “virtual DOM diffing” algorithm made popular by React, where elements of the tree are compared by tag and position between renders, and subtrees whose root tags don’t match are thrown away.

Maybe better stated as

> ... subtrees whose root tags don't match have the old version discarded and replaced by the new.

which is still clumsy, but you get the idea.

**Comment by monodop** [comment]
> And only subtrees with changes are updated

**Comment by cpryland** [comment]
Better, yes.

**Comment by brainkim** [comment]
Documentation now reads:
> Crank uses the same “virtual DOM” diffing algorithm made popular by React, where we compare elements by tag and position to reuse DOM nodes. This approach allows you to write declarative code which focuses on producing the right tree, while the framework does the dirty work of managing state and mutating the DOM.

https://crank.js.org/guides/elements#element-diffing

Let me know if you still think it is clumsy.
