### ISSUE TITLE
Crank Q&A 

### ISSUE THREAD

**Issue by brucou** [bikeshaving/crank#56]
Hi @brainkim,

I am a news editor for InfoQ. Would you be interested in an interview on Crank, its motivation, design principles and value added?

You may not necessarily know InfoQ so let me tell a few quick things about it. InfoQ's mission is to help dev teams adopt new technologies and practices. InfoQ's particularity is that content is written by software engineers/professional developers over professional writers. Our primary audience are tech leads, senior developers and software architects.

We regularly do interviews (see [here](https://www.infoq.com/news/2020/02/go-wasm-port-face-detection/)) on a variety of subjects. Let me know if that is of any interest to you. I hope this finds you well and safe in these troubled days.

Kind regards

**Comment by brainkim** [comment]
@brucou Send me an email at briankimpossible@gmail.com to coordinate! I’d be happy to answer any and all questions!

**Comment by brucou** [comment]
Great @brainkim I am deleting my post, and you should delete yours too so your email does not get picked up by spam bots.
