### ISSUE TITLE
MrBuilder plugin

### ISSUE THREAD

**Issue by jspears** [bikeshaving/crank#83]
I added a plugin to [mrbuilder](https://mr-builder.github.io/) and an [example](https://github.com/mr-builder/mrbuilder/tree/master/examples/example-crank) to make getting started with crank and mrbuilder easier.

I'll close this in a day or two.

**Comment by ryhinchey** [comment]
Cool! I see the plugin uses `babel-preset-crank`.  How’d that work out for you?

**Comment by jspears** [comment]
It worked out well -- worked as advertised.   Although the typescript typing is wonky... I am not sure what to do about that.

**Comment by brainkim** [comment]
I’m not familiar with Mr Builder but it looks cool! I will put it on my things of things to explore.

**Comment by jspears** [comment]
@brainkim If you ever want the lowdown on mrbuilder , hit me up.

Closing this.
