### ISSUE TITLE
Question regarding behavior of generator based components

### ISSUE THREAD

**Issue by mcjazzyfunky** [bikeshaving/crank#84]
@brainkim (or who else likes to help)

One of the killer features of Crank is something like the following (this `Loader` component shows a text like 'Loading...' for 4 seconds and finishes with a text like 'Finished!').

```jsx
async function* Loader() {
  for await (const { loadingText = 'Loading...', finishText = 'Finished!' } of this) { 
    yield <div>{loadingText}</div>
    await wait(4000)
    yield <div>{finishText}</div>
  }
}
```

The problem is that by the nature of the concept this `Loader` component starts reloading each time some props have been changed or the parent component has been refreshed.
Now my question: When does anybody really require/want this behavior in a real world application?
Are there really any use cases where this is desired?
Do I just miss something?

Please find below two demos (I hope the demos are self-explaining).
The React `Loader` component behaves exactly as I would expect it to behave in real world.
The Crank `Loader` component on the other hand is completely useless. 

React:
https://codesandbox.io/s/loving-volhard-515x8?file=/src/index.js

Crank:
https://codesandbox.io/s/jolly-architecture-o1xhv?file=/src/index.js

Does really nobody have a problem with this component behavior in Crank?
Thank you very, very much for your help.

**Comment by lazeebee** [comment]
If you change the loader component in the Crank example to the following then it will behave like the React example.

```js
async function* Loader() {
  let renderCount = 0;
  for await (const { loadingText = 'Loading...', finishText = 'Finished!' } of this) { 
    yield <div>{loadingText}</div>
    if (renderCount < 1) await wait(4000)
    yield <div>{finishText}</div>
    renderCount++
  }
}
```

The reason for this, in the React example the usePromise hook runs only on the first render, so when  the component refreshes, it doesn't run the promise again so it doesn't set the loading text again. But in the Crank example the promise is executed each time, so in the above code the promise is only executed on the first render.

**Comment by mcjazzyfunky** [comment]
Thanks @lazeebee 
A bit interesting that after that fix, the implementation of that Crank component has actually become more complicated (at least in lines of code/characters of code) than the React version. Of course the React version is just that simple because the example itself is quite simple, but same for the fix, that fix is also just that simple because my example is that simple. In cases where the component uses several promises all depending on certain prop values and resolving some values, things are getting a bit more hairy.

@brainkim This is a good example of why I sometimes tend to criticizes a bit that currently most Crank examples do not really cover real world patterns. In the real world - at least in non-trivial applications - there's a good chance that a lot of your components have multiple props, are localizable and themeable (let's say using a css-in-js solution) and have side-effects that depend on some prop values.
They have to be prepared that in almost any moment the context value for the current theme can change or the used language or some props in general.

So this simple

```
yield await something(...)
yield await somethingElse(...)
...
```

pattern will actually  in many cases not really work in this simplicity.
Maybe adding some more sophisticated examples to the Crank documentation sometime in future would be really helpful - thanks for that in advance :-)

Thanks a lot to everybody ... will close this issue now...

**Comment by brainkim** [comment]
Sorry I didn’t get to respond before it closed. One thing you could do is keep track of promises in the async generator component, and only kick off an async request if props require it. So you could do something like:

```jsx
async function *Loader(props) {
  let fetchResult;
  for await (const newProps of this) {
    if (fetchResult == null || needsFetch(props, newProps)) {
      yield <div>Loading...</div>;
      fetchResult = await myFetchAPI(newProps);
      props = newProps;
    }
    yield <Result>{fetchResult.toString()</Result>;
  }
}
```

Essentially, with generators you get useMemo for free!

**Comment by brainkim** [comment]
I’ve also signed up the repository for GitHub discussions so if you’d like to ask questions without worrying about when to close the issue you can hit up the discussions tab!
