### ISSUE TITLE
Skip rendering after prop update

### ISSUE THREAD

**Issue by lazeebee** [bikeshaving/crank#85]
How can you skip an update after a prop update as you need to yield on each iteration?

**Comment by brainkim** [comment]
If you have a stateful component you can render a special `<Copy />` element instead of what you rendered previously to prevent the children from updating.

```tsx
function equals(props, newProps) {
  for (const name in {...props, ...newProps}) {
    if (props[name] !== newProps[name]) {
      return false;
    }
  }

  return true;
}

function memo(Component) {
  return function *Wrapped({props}) {
    yield <Component {...props} />;
    for (const newProps of this) {
      if (equals(props, newProps)) {
        yield <Copy />;
      } else {
        yield <Component {...newProps} />;
      }

      props = newProps;
    }
  };
}
```

**Comment by brainkim** [comment]
You can read more about the special element tags here: https://crank.js.org/guides/special-tags-and-props

**Comment by ryhinchey** [comment]
That’s beautiful

**Comment by lazeebee** [comment]
Wouldn't it be possible to implement this feature with yield null?

**Comment by ryhinchey** [comment]
@lazeebee I’m pretty sure that `yield null`will make your component render nothing which is what most would expect to happen.  `Copy` will keep the UI the same without actually calling render again
